replicaCount: 1

image:
  repository: 655307635386.dkr.ecr.us-west-2.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: django_db
  POSTGRES_USER: django_user
  POSTGRES_PASSWORD: pass9764gd

resources: {}

